version: '3.8'
services:
  # server:
    # build: ./server
    # container_name: expserver
    # ports:
    #   - 5000:5000
  db:
    build: ./database
    container_name: mysqlserver
    expose:
      - '3306'
    ports:
      - 3306:3306
    secrets:
      - db_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
secrets:
  db_password:
      file:  ./dbpass.file



